-- 코드를 입력하세요
# 상품코드 별 매출액(판매가 * 판매량)
# GROUY BY 상품코드
# 매출액 기준 내림차순 / 상품코드 오름차순

SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC