-- 코드를 입력하세요
# 2021년 가입
# 상품 구매 / 전체 회원수 (비율)
# 년 / 월 별로 출력
# 비율은 소수점 둘째자리에서 반올림
# 년을 기준 오름차순
# 월을 기준으로 오름차순

SELECT YEAR(O.SALES_DATE), MONTH(O.SALES_DATE),
COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
ROUND(
    COUNT(DISTINCT O.USER_ID) / (
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE YEAR(JOINED) = 2021
    ),1
)
AS PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO U
ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE) ASC, MONTH(O.SALES_DATE) ASC
