-- 코드를 작성해주세요
# 스킬코드는 2의 제곱수로 구성 ..... BIT
# ID 기준 오름차순

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S
ON (D.SKILL_CODE & S.CODE) != 0 # 비트 계산
WHERE S.CATEGORY = 'Front End'
ORDER BY D.ID