-- 코드를 입력하세요
SELECT T.TITLE, T.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, R.CREATED_DATE
FROM USED_GOODS_BOARD T
JOIN USED_GOODS_REPLY R
ON T.BOARD_ID = R.BOARD_ID
WHERE YEAR(T.CREATED_DATE) = 2022 AND MONTH(T.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, T.TITLE ASC